--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: articles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    contenu text NOT NULL,
    date_publication timestamp(6) without time zone NOT NULL,
    titre character varying(255) NOT NULL
);


ALTER TABLE public.articles OWNER TO postgres;

--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commentaires; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.commentaires (
    id bigint NOT NULL,
    auteur character varying(255) NOT NULL,
    contenu text NOT NULL,
    date_commentaire timestamp(6) without time zone NOT NULL,
    article_id bigint NOT NULL
);


ALTER TABLE public.commentaires OWNER TO postgres;

--
-- Name: commentaires_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.commentaires ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commentaires_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: 57507; Type: BLOB; Schema: -; Owner: postgres
--

SELECT pg_catalog.lo_create('57507');


ALTER LARGE OBJECT 57507 OWNER TO postgres;

--
-- Name: 57508; Type: BLOB; Schema: -; Owner: postgres
--

SELECT pg_catalog.lo_create('57508');


ALTER LARGE OBJECT 57508 OWNER TO postgres;

--
-- Data for Name: articles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.articles (id, contenu, date_publication, titre) FROM stdin;
1	57507	2025-05-31 11:34:19.716868	Mon Premier Article de Blog
2	57508	2025-05-31 11:44:52.195503	Les Bases de Spring Boot
\.


--
-- Data for Name: commentaires; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.commentaires (id, auteur, contenu, date_commentaire, article_id) FROM stdin;
1	Arthur H	Excellent article ! Très inspirant. J'ai vraiment apprécié la section sur la persévérance.	2025-05-31 11:49:31.079963	1
2	Junior	Merci pour cette introduction à Spring Boot ! J'ai hâte d'en apprendre plus.	2025-05-31 13:30:28.643586	2
3	jude	Très bon point sur la persévérance ! C'est vraiment la clé pour progresser dans le développement. J'attends avec impatience les prochains articles.	2025-05-31 13:58:43.310364	1
4	grant	Article très clair sur les bases de Spring Boot. Serait-il possible d'avoir un article futur sur l'intégration de bases de données NoSQL avec Spring Data ?	2025-05-31 14:00:28.690521	2
\.


--
-- Name: articles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.articles_id_seq', 2, true);


--
-- Name: commentaires_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.commentaires_id_seq', 4, true);


--
-- Data for Name: BLOBS; Type: BLOBS; Schema: -; Owner: -
--

BEGIN;

SELECT pg_catalog.lo_open('57507', 131072);
SELECT pg_catalog.lowrite(0, '\x4365636920657374206c6520636f6e74656e752064c3a97461696c6cc3a9206465206d6f6e20746f7574207072656d6965722061727469636c652e20496c207061726c65206465206c27696d706f7274616e6365206465206c612070657273c3a976c3a972616e636520656e2070726f6772616d6d6174696f6e2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('57508', 131072);
SELECT pg_catalog.lowrite(0, '\x556e2061706572c3a7752064657320636f6d706f73616e747320636cc3a97320646520537072696e6720426f6f74206574206465206c657572207574696c6974c3a920706f7572206c652064c3a976656c6f7070656d656e74207261706964652064276170706c69636174696f6e732e');
SELECT pg_catalog.lo_close(0);

COMMIT;

--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: commentaires commentaires_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commentaires
    ADD CONSTRAINT commentaires_pkey PRIMARY KEY (id);


--
-- Name: articles uk3veovm5eqxuqxc83c6vly1fbr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT uk3veovm5eqxuqxc83c6vly1fbr UNIQUE (titre);


--
-- Name: commentaires fkj1jy041e3qu2sas505gailad0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commentaires
    ADD CONSTRAINT fkj1jy041e3qu2sas505gailad0 FOREIGN KEY (article_id) REFERENCES public.articles(id);


--
-- PostgreSQL database dump complete
--

